language: go
go:
  - 1.11.x
  - master

os:
  - linux
  - osx

dist: trusty
sudo: false
install: true

env:
  - GO111MODULE=on
script:
  - go vet ./...
  - go test -race ./...
  - go test -cover ./...

after_success:
  - go test -run=NONE -bench . -benchmem ./...
