image: golang:latest
pipelines:
  default:
    - step:
        caches:
          - gopath
        script:
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/xmpp"
          - cd "$GOPATH/src/mellium.im/xmpp"
          - go-wrapper download
          - go version
          - go env
          - make vet
          - make test
          - make bench
definitions:
  caches:
    gopath: mkdir -p "$GOPATH/src/"
