image: golang:latest
pipelines:
  default:
    - step:
        caches:
          - vendor
        script:
          - export PATH="/gosrc/bin:$PATH"
          - go get -u github.com/golang/dep/cmd/dep
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/xmpp"
          - cd "$GOPATH/src/mellium.im/xmpp"
          - cp -r /vendor $GOPATH/src/mellium.im/xmpp/vendor || true
          - dep ensure
          - go version
          - go env
          - go vet ./...
          - go test -race ./...
          - go test -cover -bench . -benchmem ./...
          - cp -r $GOPATH/src/mellium.im/xmpp/vendor /vendor
definitions:
  caches:
    vendor: /vendor
