image: golang:1.8
pipelines:
  default:
    - step:
        script:
          - uname -a; true
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/xmpp"
          - cd "$GOPATH/src/mellium.im/xmpp"
          - go-wrapper download
          - go version
          - make vet
          - make test
          - go build -race
          - make bench
