image: golang:latest
pipelines:
  default:
    - step:
        script:
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/xmpp"
          - cd "$GOPATH/src/mellium.im/xmpp"
          - go-wrapper download
          - go build -race
          - make test
          - make bench
