image: golang:latest
pipelines:
  default:
    - step:
        caches:
          - vendor
          - gosrc
        script:
          - export PATH="/gosrc/bin:$PATH"
          - /bin/bash -c '[[ -e /gosrc/bin ]] || git clone --depth=1 https://go.googlesource.com/go /gosrc'
          - /bin/bash -c '[[ -e /gosrc/bin ]] || (cd /gosrc/src && ./make.bash)'
          - go get -u github.com/golang/dep/cmd/dep
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/xmpp"
          - cd "$GOPATH/src/mellium.im/xmpp"
          - dep ensure
          - go version
          - go env
          - make ci
          - cp -r $GOPATH/src/mellium.im/xmpp/vendor /vendor
definitions:
  caches:
    vendor: /vendor
    gosrc: /gosrc
